name: CD

on:
  push:
    branches:
     - main

jobs:
  docs:
    name: Deploy API Documentation
    runs-on: ubuntu-latest

      - name: Install dependencies
        run: python -m pip install myst-parser numpy numpydoc sphinx sphinx-book-theme

      - name: Build API documentation
        run: |
          sphinx-apidoc -Mfeo docs/source mycosmo
          sphinx-build docs/source docs/build

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build

before_script:
  - python --version 
  - python -m pip install pytest pytest-cov pytest-emoji pytest-pydocstyle
  - python -m pip install myst-parser numpy numpydoc sphinx sphinx-book-theme

pages:
  script:
    - sphinx-apidoc -Mfeo docs/source mycosmo
    - sphinx-build docs/source docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public
  only:
      - main

